id: self-healing-orchestrator
namespace: devops.healing
description: Main orchestration flow for incident detection and auto-fix

variables:
 mcp_server_url: "http://mcp-server:3001" || "https://mcp-server-deploy.up.railway.app"
  dashboard_url: "http://dashboard:3000" || "https://autosre.vercel.app"

triggers:
  - id: webhook-trigger
    type: io.kestra.plugin.core.trigger.Webhook
    key: "incident-webhook"

inputs:
  - id: log_source
    type: STRING
    defaults: "demo"
  - id: raw_log
    type: STRING
    defaults: ""
  - id: severity
    type: STRING
    defaults: ""
  - id: category
    type: STRING
    defaults: ""
  - id: summary
    type: STRING
    defaults: ""
  - id: suggested_fix
    type: STRING
    defaults: ""

tasks:
  - id: normalize-input
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.11-slim
    script: |
      import json
      import random
      from datetime import datetime

      # Get inputs
      raw_log = """{{ inputs.raw_log }}""".strip()
      log_source = """{{ inputs.log_source }}""".strip()

      # Demo log scenarios if no input provided
      demo_logs = [
        {
          "message": "FATAL: Connection pool exhausted - max_connections=100 exceeded",
          "source": "postgresql"
        },
        {
          "message": "ERROR: Memory usage exceeded 95% threshold on node-3",
          "source": "prometheus"
        },
        {
          "message": "CRITICAL: Auth service returning 503 - unable to validate tokens",
          "source": "auth-service"
        }
      ]

      if not raw_log:
        selected_log = random.choice(demo_logs)
        raw_log = selected_log["message"]
        log_source = selected_log["source"]

      normalized = {
        "timestamp": datetime.now().isoformat(),
        "source": log_source or "unknown",
        "message": raw_log,
        "raw": raw_log
      }

      print(json.dumps(normalized))

  - id: analyze-or-use-provided
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.11-slim
    script: |
      import json
      import re

      # Check if severity/category were provided directly
      provided_severity = """{{ inputs.severity }}""".strip()
      provided_category = """{{ inputs.category }}""".strip()
      provided_summary = """{{ inputs.summary }}""".strip()
      provided_fix = """{{ inputs.suggested_fix }}""".strip()

      if provided_severity and provided_category:
        # Use provided values from monitoring script
        analysis = {
          "severity": provided_severity,
          "category": provided_category,
          "summary": provided_summary or "Incident detected",
          "suggested_fix": provided_fix or "Manual investigation required",
          "affected_file": None,
          "confidence": 0.9
        }
      else:
        # Simple rule-based analysis (no external AI needed for demo)
        log_data = json.loads("""{{ outputs['normalize-input'].vars.stdout }}""")
        message = log_data.get("message", "").lower()

        # Determine severity
        if "fatal" in message or "critical" in message or "oom" in message:
          severity = "critical"
        elif "error" in message or "fail" in message:
          severity = "high"
        elif "warn" in message:
          severity = "medium"
        else:
          severity = "low"

        # Determine category
        if any(word in message for word in ["database", "postgres", "mysql", "connection pool", "max_connections"]):
          category = "database"
        elif any(word in message for word in ["memory", "oom", "heap", "ram"]):
          category = "memory"
        elif any(word in message for word in ["disk", "storage", "space"]):
          category = "disk"
        elif any(word in message for word in ["network", "timeout", "connection refused"]):
          category = "network"
        elif any(word in message for word in ["auth", "login", "permission", "403", "401"]):
          category = "auth"
        else:
          category = "application"

        # Generate summary
        summary = log_data.get("message", "Unknown incident")[:100]

        # Suggest fix based on category
        fixes = {
          "database": "Check database connections and increase max_connections if needed",
          "memory": "Increase memory limits or investigate memory leaks",
          "disk": "Clean up disk space or expand storage",
          "network": "Check network connectivity and firewall rules",
          "auth": "Verify credentials and authentication configuration",
          "application": "Check application logs for detailed error information"
        }

        analysis = {
          "severity": severity,
          "category": category,
          "summary": summary,
          "suggested_fix": fixes.get(category, "Manual investigation required"),
          "affected_file": None,
          "confidence": 0.7
        }

      print(json.dumps(analysis))

  - id: create-incident
    type: io.kestra.plugin.core.http.Request
    uri: "{{ vars.mcp_server_url }}/incidents"
    method: POST
    contentType: application/json
    body: |
      {
        "severity": "{{ json(outputs['analyze-or-use-provided'].vars.stdout).severity }}",
        "category": "{{ json(outputs['analyze-or-use-provided'].vars.stdout).category }}",
        "summary": "{{ json(outputs['analyze-or-use-provided'].vars.stdout).summary }}",
        "description": "{{ json(outputs['normalize-input'].vars.stdout).message }}",
        "suggested_fix": "{{ json(outputs['analyze-or-use-provided'].vars.stdout).suggested_fix }}",
        "raw_log": "{{ json(outputs['normalize-input'].vars.stdout).message }}",
        "source": "{{ json(outputs['normalize-input'].vars.stdout).source }}",
        "kestra_execution_id": "{{ execution.id }}",
        "confidence": {{ json(outputs['analyze-or-use-provided'].vars.stdout).confidence }}
      }

  - id: log-incident-created
    type: io.kestra.plugin.core.log.Log
    message: |
      Incident created: {{ json(outputs['create-incident'].body).id }}
      Severity: {{ json(outputs['analyze-or-use-provided'].vars.stdout).severity }}
      Category: {{ json(outputs['analyze-or-use-provided'].vars.stdout).category }}
      Summary: {{ json(outputs['analyze-or-use-provided'].vars.stdout).summary }}

  - id: check-severity
    type: io.kestra.plugin.core.flow.If
    condition: "{{ json(outputs['analyze-or-use-provided'].vars.stdout).severity == 'critical' or json(outputs['analyze-or-use-provided'].vars.stdout).severity == 'high' }}"
    then:
      - id: trigger-autofix
        type: io.kestra.plugin.core.flow.Subflow
        namespace: devops.healing
        flowId: auto-fix-workflow
        wait: false
        inputs:
          incident_id: "{{ json(outputs['create-incident'].body).id }}"
          severity: "{{ json(outputs['analyze-or-use-provided'].vars.stdout).severity }}"
          summary: "{{ json(outputs['analyze-or-use-provided'].vars.stdout).summary }}"
    else:
      - id: log-low-severity
        type: io.kestra.plugin.core.log.Log
        message: "Low/Medium severity incident logged - no auto-fix triggered"

errors:
  - id: error-handler
    type: io.kestra.plugin.core.log.Log
    message: "Error in orchestrator flow"
